// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    EditorMarkdown: typeof import('./../src/components/editor/markdown.vue')['default']
    EditorWangEditor: typeof import('./../src/components/editor/wangEditor.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElButtonGroup: typeof import('element-plus/es')['ElButtonGroup']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElPopconfirm: typeof import('element-plus/es')['ElPopconfirm']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ElUpload: typeof import('element-plus/es')['ElUpload']
    FormButton: typeof import('./../src/components/form/button.vue')['default']
    FormError: typeof import('./../src/components/form/error.vue')['default']
    FormFieldList: typeof import('./../src/components/form/fieldList.vue')['default']
    FormInput: typeof import('./../src/components/form/input.vue')['default']
    FormVeeValidateError: typeof import('./../src/components/form/veeValidateError.vue')['default']
    HdAnimateList: typeof import('./../src/components/hd/animateList.vue')['default']
    HdBreadcrumb: typeof import('./../src/components/hd/breadcrumb.vue')['default']
    HdCaptcha: typeof import('./../src/components/hd/captcha.vue')['default']
    HdCode: typeof import('./../src/components/hd/code.vue')['default']
    HdFullscreen: typeof import('./../src/components/hd/fullscreen.vue')['default']
    HdNotification: typeof import('./../src/components/hd/notification.vue')['default']
    HdTab: typeof import('./../src/components/hd/tab.vue')['default']
    SiteItem: typeof import('./../src/components/site/item.vue')['default']
    UploadSingleImage: typeof import('./../src/components/upload/singleImage.vue')['default']
    UserDrop: typeof import('./../src/components/user/drop.vue')['default']
    UserList: typeof import('./../src/components/user/list.vue')['default']
  }
}

export { }
